name: Java CI

on:
   workflow_dispatch:
    inputs:
     name:
      default: Tobias
      required: true

jobs:
     
  build:
    runs-on: windows-latest

    steps:
      - run: echo "Moin ${{ github.event.inputs.name }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v3
        with:
         name: Package
         path: build/jar